version: "3"
services:
  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=inituser
      - DOCKER_INFLUXDB_INIT_PASSWORD=initpass
      - DOCKER_INFLUXDB_INIT_ORG=first-org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket01
    volumes:
      # Make sure you create these local directories
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
    networks:
      - tig_network
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5

  # telegraf:
  #   image: telegraf:1.28.2-alpine
  #   container_name: telegraf
  #   user: "1000:1000"
  #   volumes:
  #     # Make sure you create this local directory
  #     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
  #   restart: unless-stopped
  #   networks:
  #     - tig_network
  #   depends_on:
  #     # Waits until influxdb container is up
  #     influxdb:
  #       condition: service_healthy

  grafana:
    image: grafana/grafana-oss:9.5.12
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    ports:
      - 3000:3000
    volumes:
      # Make sure you create these local directories
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config:/etc/grafana
      - ./grafana/log:/var/log/grafana
    restart: unless-stopped
    networks:
      - tig_network

networks:
  tig_network:
    driver: bridge
